### ISSUE TITLE
epub and kindle files recognised as different formats

### ISSUE THREAD

**Issue by workflowsguy** [richardlehane/siegfried#121]
While ".docx" is correctly recognized as "Microsoft Word for Windows" and not as ".zip", e.g. ".epub" is not.
Also, the kindle ".azw3" format is not recognised as such, but as ".mobi" (which might technically be true, but the original file format nameis still correct).

Thanks!

**Comment by richardlehane** [comment]
Hi workflowsguy,
I don't think there is a [PRONOM ID](http://www.nationalarchives.gov.uk/PRONOM/BasicSearch/proBasicSearch.aspx?status=new) for kindle .azw3 files & suspect that's why those files are defaulting to .mobi. You can make requests for new PRONOM IDs here: https://www.nationalarchives.gov.uk/contact-us/submit-information-for-pronom/.

There is an ID for .epub ([fmt/483](http://www.nationalarchives.gov.uk/PRONOM/fmt/483)) & this should match. The test epub files I have access to do match successfully so this might be something specific to your epub files. Are you able to share a sample on this ticket so that I can take a look?

thanks for this report,
Richard

**Comment by workflowsguy** [comment]
Hello Richard,

I got confused by my own workflow (and scripts) regarding epubs. They are all recognized correctly.
Apologies for raising a false alarm.

Regarding the .azw(3) files, I will make a PRONOM request.

Thanks!

**Comment by richardlehane** [comment]
good to hear, thanks for letting me know - closing this now
