### ISSUE TITLE
Can't detect plan9 platform executable program files.

### ISSUE THREAD

**Issue by smcduck** [richardlehane/siegfried#132]
`env GOOS=plan9 arch=386 go build helloworld.go`

sf can't detect anything from this plan9 executable program file.

Great job. thank you!

**Comment by richardlehane** [comment]
thanks for reporting this, Scrooge. 

sf implements file format signatures defined elsewhere: e.g. the [PRONOM database](http://www.nationalarchives.gov.uk/PRONOM/Default.aspx) or [freedesktop.org](https://www.freedesktop.org/wiki/Software/shared-mime-info/). In order to get sf to recognise a plan9 executable, you'd need to get one of those projects to publish a signature for it. PRONOM have a web form for proposing new signatures. freedesktop.org have a Bugzilla tracker.

A good place to start if proposing a new file format signature would be the magic bytes at the start of a plan9 executable which are described here: [https://www.freedesktop.org/wiki/Software/shared-mime-info/
](https://www.freedesktop.org/wiki/Software/shared-mime-info/
)

Another option is to use the `roy` tool to build your own signature file with a custom extension. This would allow you to define your own signature without going upstream to those projects. The command you need for this is `roy build -extend mysig.xml`. More info on that here: [https://www.freedesktop.org/wiki/Software/shared-mime-info/
](https://github.com/richardlehane/siegfried/wiki/Building-a-signature-file-with-ROY#customisable)

**Comment by smcduck** [comment]
have reported to PRONOM database

**Comment by richardlehane** [comment]
closing, as this now with PRONOM
