### ISSUE TITLE
Ubuntu/Debian installation procedure not working

### ISSUE THREAD

**Issue by hmiguim** [richardlehane/siegfried#163]
The repository for siegfried on bintray is not reachable anymore. It gives me a forbidden message. 

```bash
Err:5 http://dl.bintray.com/siegfried/debian wheezy/main amd64 Packages
  403  Forbidden [IP: X.X.X.X]
Ign:7 http://dl.bintray.com/siegfried/debian wheezy/main all Packages
Reading package lists...
W: The repository 'http://dl.bintray.com/siegfried/debian wheezy Release' does not have a Release file.
E: Failed to fetch http://dl.bintray.com/siegfried/debian/dists/wheezy/main/binary-amd64/Packages  403  Forbidden [IP: X.X.X.X]
```

**Comment by szymon3** [comment]
I realized that bintray randomly returns 403 error. Right now, installation is working fine, but yesterday afternoon I couldn't complete it due to above error.

**Comment by asabellico** [comment]
could it be due to the warning shown on top here https://bintray.com/ ?

**Comment by richardlehane** [comment]
as @asabellico notes, this is due to the bintray end-of-life. 

Apologies: I've been working on an alternate host for the debian package, but have not yet finished that work.

If you've already got siegfried installed and are up-to-date, then I'd recommend removing the bintray repository from your apt sources list. I will provide an alternate debian option prior to the next release.

To do this: open "/etc/apt/sources.list" and delete the line "deb http://dl.bintray.com/siegfried/debian wheezy main"

If you are trying to do a new siegfried install, please either wait for the next release (it is due shortly) or use on of the other install methods: compile from source or use the brew package with linux brew.

**Comment by dnarc** [comment]
I was going to stand up a docker image exposing the network port as an
alternative but I couldn't find any documentation on how to use the web
API. Is there some documentation on how to use it somewhere?

**Comment by richardlehane** [comment]
Hi @dnarc 
There's a page on the [wiki](https://github.com/richardlehane/siegfried/wiki/Using-the-siegfried-server).
When you start the server (e.g. with `sf -serve :5050`) you can also visit whatever host:port you gave in a browser (e.g. http://localhost:5050) and you'll see documentation there too.

**Comment by richardlehane** [comment]
I'm now self-hosting the ubuntu/deb repository, in place of the old bintray repository.

**To remove the old repository, open "/etc/apt/sources.list" and delete the line "deb http://dl.bintray.com/siegfried/debian wheezy main".**

To install the new repository, do the following:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20F802FE798E6857
sudo add-apt-repository "deb https://www.itforarchivists.com/ buster main"
sudo apt-get update && sudo apt-get install siegfried
```

Please comment on this ticket if you encounter any issues.
