### ISSUE TITLE
It for archivist encoding/return issues

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#193]
Demoing today I spotted some (JSON?) encoding issues in the ITForArchivists interfaces. (Verified on Edge and Chrome)

1. Drag and drop receives a 502 error and unexpected token:

![image](https://user-images.githubusercontent.com/1880412/171642051-20ec2b0f-2195-4c37-97cb-0c1ba5ac4b6f.png)

2. Select file and submit receives a 500 and 404: 

![image](https://user-images.githubusercontent.com/1880412/171642281-2bb7ee8f-4c2e-46bc-98c2-677ff517cce3.png)

It should be possible to verify with any particular format whether dragging or selecting. I was using 7z, PDF, and GIF.

**Comment by richardlehane** [comment]
thanks for letting me know Ross, I know where I broke the drag'n'drop identify (it is trying to load a signature file that isn't there) & will fix tonight. 

The second error is because that upload isn't for an arbitrary file, it is only for results files (YAML, JSON, CSV) to give a chart of your results.

**Comment by ross-spencer** [comment]
> The second error is because that upload isn't for an arbitrary file, it is only for results files (YAML, JSON, CSV) to give a chart of your results.

Oh doh!! I see now! thx for clarifying!

**Comment by richardlehane** [comment]
thanks for letting me know about this one Ross, it is now fixed
