### ISSUE TITLE
Looks like siegfried version 1.10.0 requires Go 1.20

### ISSUE THREAD

**Issue by diamondap** [richardlehane/siegfried#224]
Our code includes siegfried v. 1.10.0 in our go.mod files, and we build siegfried into our binary. When trying to build a Docker container using Go 1.17, we run into this error:

```
#0 10.16 note: module requires Go 1.20
#0 10.16 Building file_restorer binary
#0 10.49 # github.com/richardlehane/siegfried/pkg/wikidata
#0 10.49 /go/pkg/mod/github.com/richardlehane/siegfried@v1.10.0/pkg/wikidata/load_wikidata.go:74:31: undefined: any
#0 10.49 /go/pkg/mod/github.com/richardlehane/siegfried@v1.10.0/pkg/wikidata/load_wikidata.go:79:17: undefined: any
```
The changelog for this release should mention that this version requires Go >=1.20. Note that upgrading to Go 1.20 does fix the problem.

**Comment by richardlehane** [comment]
Hi Andrew, apologies for causing this disruption. I'll patch the changelog & make sure to note similar updates in future releases

**Comment by diamondap** [comment]
No problem. Thanks for the quick response.

**Comment by richardlehane** [comment]
Hi Andrew, I've patched the changelog and readme to reflect the change in minimum go version required. It turns out that versions 1.18+ work so I downgraded the requirement in the go.mod file. Have also added go versions 1.18+ to the test matrix in the github action so that this is better tracked in future
