### ISSUE TITLE
sf -update failing

### ISSUE THREAD

**Issue by despens** [richardlehane/siegfried#39]
I installed siegfried via the debian repository on Ubuntu 14.04 64 bit.

Update failure:
```sh
$ sf -update
... downloading latest signature file ...
2015/07/02 16:42:55 Siegfried: error updating signature file, Siegfried: error writing to directory, open /usr/share/siegfried/pronom.gob: permission denied
```

```sh
$ ll /usr/share/siegfried/
total 3136
drwxr-xr-x   4 root root    4096 Jul  2 16:39 ./
drwxr-xr-x 470 root root   20480 Jul  2 16:39 ../
-rw-r--r--   1 root root  626745 Mar 22 07:48 archivematica.gob
-rw-r--r--   1 root root  104869 Mar 22 07:48 container-signature-20150218.xml
drwxr-xr-x   2 root root    4096 Jul  2 16:39 custom/
-rw-r--r--   1 root root 1746928 Mar 22 07:48 DROID_SignatureFile_V81.xml
drwxr-xr-x   2 root root   65536 Jul  2 16:39 pronom/
-rw-r--r--   1 root root  626127 Mar 22 07:48 pronom.gob
```
OK, try as root:
```sh
$ sudo sf -update
... downloading latest signature file ...
... writing /usr/share/siegfried/pronom.gob ...
Your signature file has been updated
```

But after:
```sh
$ sf Q1330
2015/07/02 16:47:57 Error: error loading signature file, got: Siegfried: error reading signature file; got gob: unknown type id or corrupted data
Try running `sf -update`
```

I'm not sure if this is because the UK National Archives changed the URLs where the pronom profiles are stored?

**Comment by richardlehane** [comment]
Hi Dragan
thanks for this report. Can you check `siegfried -version` for me?

What seems to be going wrong is that:

1) I suspect you are running 1.0.0
2) the update service has 1.1.0 signatures (the signature format changed between those releases, causing your load error)
3) the `sf -update` command should have prevented you getting into this situation (it should have warned you to upgrade before updating) and didn't for some reason.

I'm planning  a little work on `sf -update` for the 1.2.0 release and will dig into number 3) more then.
I'll also see if I can get the bintray packages updated to 1.1.0 in order to fix this for you. Until that happens I'm afraid you won't be able to run `sf -update` successfully but you could get `sf` running again on the older signature file by hosing your install and reinstalling.

Thanks again for the report,
Richard

**Comment by richardlehane** [comment]
I should also have mentioned: if you are happy to build your own signature file, there is no need to reinstall, & you can also run `sf` with latest PRONOM signatures.

If you run `sudo roy build` your old signature file should be restored (I think the Deb release has all it needs to do this). If not, follow instructions that follow.

You can update to latest PRONOM signatures by following the instructions on this page: https://github.com/richardlehane/siegfried/wiki/Building-a-signature-file-with-ROY

**Comment by despens** [comment]
Thanks! Yes indeed, running 1.0.0, but happy with the results anyway. It's OK to wait for the 1.1.0 to be available in the debian repository.

**Comment by despens** [comment]
Can confirm that it works flawlessly with 1.1.0.
Closing the issue.
