### ISSUE TITLE
Feature request: Analysis of WARC files

### ISSUE THREAD

**Issue by despens** [richardlehane/siegfried#43]
Siegfried works great with ZIP archives.

It would be even greater if it could work with WARC as well, the ISO standard web archiving format. Web archiving is gaining importance, and there are no comfortable tools to do any more sophisticated analysis that maybe extracting included mime types--which is not detailed enough.

At the moment, it is possible to sort-of convert a WARC to ZIP via [warctozip](/alard/warctozip) and then have Siegfried look inside. That's kind of clumsy though, and the tool is not able to represent different time versions of the same URL.

**Comment by richardlehane** [comment]
Happy to add this in Dragan. To avoid proliferation of flags, suggest I include this as a supported decompression type (i.e. to the existing "-z" flag which would then work for zip, tar, gzip and warc)... is that appropriate?

**Comment by despens** [comment]
This is great, thank you! Yes, the `-z` flag would make sense.

The `filename` then should be output in the form `<warc-filename>/<capture-date>/<orignal-url>`, like it is usually done for web archives. 

Example:
`yelp.warc.gz/20150214002555/http://www.yelp.com/user_details?userid=IryXs5C2_fYI2Fgd4yEdLw`

This makes it possible to address the recorded response in the warc file and get other information from it, if required.

**Comment by ampoffcom** [comment]
+1

**Comment by richardlehane** [comment]
saw this on twitter today from @atomotic - https://gist.github.com/atomotic/2c85a5971d28fb2f4e80

**Comment by richardlehane** [comment]
Hi Dragan
I *think* this feature is now ready. Supports unpacking both WARC and ARC with -z flag, using [github.com/richardlehane/webarchive](github.com/richardlehane/webarchive)

I'll do testing over the weekend and will try to get a 1.3 release finalised over the next week. If you're able to compile from master and do some tests yourself, would be much appreciated.

**Comment by atomotic** [comment]
👍
after installing with `go get` i needed to manually copy pronom.sig as explained in  https://github.com/richardlehane/siegfried/issues/53
i tested with small warcs until now and seems perfect

**Comment by richardlehane** [comment]
At this stage I think it should work well on large uncompressed WARC and ARC files but expect it to perform terribly on large gzipped WARCs and ARCs. This is because currently it will try to copy the whole uncompressed file into multiple buffers in memory and will eat up all your RAM. I'm hoping to get a fix for this shortly but would be interested in hearing how users go with gizipped WARCs and ARCs of different sizes... i.e. how big does the file need to be before performance really suffers?

The other thing that won't work yet is continuation records that span multiple WARC files. E.g. you've got part of a record in file1.warc.gz and the second part in file2.warc.gz. The webarchive library should support this but I haven't rolled it into sf as yet. Do many people use this WARC feature? I hope to have a fix for this too shortly and would be great to have some example WARC files to test it on if anybody has some to hand.

Finally, the underlying github.com/richardlehane/webarchive is brand new and may well have issues of its own - very interested to hear of any failures to correctly unpack specific WARC or ARC files.

thanks for testing!
Richard
