### ISSUE TITLE
Siegreader fatal error while attempting to mmap: %s; error: Not enough storage is available to process this command [v.1.2.2 win32]

### ISSUE THREAD

**Issue by yrad** [richardlehane/siegfried#50]
Siegfried Version 1.2.2 (win 32)
Siegreader fatal error while attempting to mmap: %s; error: Not enough storage is available to process this command.

Occurs when processing *.dv files >1GB. Less than 1GB succeeds with an extension match:

>: pronom
>: x-fmt/152
>: 'Digital Video'
>:
>: 'video/dv'
>: 'extension match'
>: 'match on extension only'

Other media files of similar sizes (*.m4v and *.mov) are unaffected. 

Let me know what I can do to help troubleshoot.

I should add that this error occurs when processing files on their own. In processing a directory of *.dv files larger than 1GB, a 

>panic: runtime error: slice bounds out of range* 

is returned.

**Comment by richardlehane** [comment]
Hi Duncan
thanks very much for this report. 

The reader *should* switch to a special big file mode when a file is too large to mmap on a particular architecture. I'll investigate what is preventing this for you. Can I ask - what is the smallest file size that produces this error?

Re. the different media types not being effected: this is because sf will quit scanning early whenever it can (following a positive match with no possible superior matches), so doesn't always need to load the whole file. In the case of DV files, these are treated as unknown (because there is no matching byte signature) and sf will do an exhaustive check of the whole file.

I'll prioritise fixing this bug & will update this shortly.

cheers
Richard

**Comment by richardlehane** [comment]
Hi Duncan
I've pushed a change that I hope will catch this bug and have updated the Win32 1.2.2 download on the releases page. It would be great if you could replace your sf binary with this latest and try those files again. Because sf will do a full scan, identification will take a long time (perhaps even minutes) but it should hopefully not panic.
cheers
Richard

**Comment by yrad** [comment]
Thanks for getting a read on this so quickly. And thanks for the explanation, too. No rest for the wicked, eh?

I've done some quick tests with the newest version and it handles sizes up to 2GB (i.e. 2147483640 bytes - a hair off 2GB in base2 - gives me an extension match, whereas 2147483648 bytes - 2GB - returns a panic). The error returned is a panic - not the fatal mmap error I'd experienced earlier.

And in case it's worth mentioning, the smallest size the previous version could handle without an mmap error was somewhere between 1.01 and 1.001GB.

**Comment by richardlehane** [comment]
Hi Duncan
I'm sorry, catching your mmap error exposed a lot of sloppy integer overflow bugs in the big file handling code (just where you'd expect these to be properly handled!). I *think* these are all fixed now. I've updated the win32 1.2.2 release with the changes.
cheers
Richard

**Comment by yrad** [comment]
Nicely done! I can't force the error anymore. 

Thank you.
