### ISSUE TITLE
pronom.sig problem

### ISSUE THREAD

**Issue by seamang** [richardlehane/siegfried#53]
Siegfried rejecting pronom.sig:

$ sf -update
... downloading latest signature file ...
... writing /home/[user]/siegfried/pronom.sig ...
Your signature file has been updated

$ sf test.txt
2015/09/04 11:27:49 Error: error loading signature file, got: siegfried: not a siegfried signature file; try running `sf -update`

$ ls -al /home/[user]/siegfried/pronom.sig
-rwxrwxr-x 1 [user] [user] 86540 Sep  4 11:29 /home/[user]/siegfried/pronom.sig

I'm a complete go newbie, and haven't got the hang of the environment enough yet even to start trying simple print tests.

**Comment by seamang** [comment]
I'm using the current version pulled down using 'go get github.com/richardlehane/siegfried/cmd/sf'. Having just seen issue #49, I guess this version ought to be ok?

**Comment by richardlehane** [comment]
Hi Graham
sorry, this the fault of my poor git usage - I'm terrible with git so tend to just do everything on master rather than use branches properly. Master *should* point to the latest stable release (1.2.2), and I should do development on branches (and I sometimes do!), but is currently pointing to the latest code. The latest code is incompatible with the 1.2.2-based pronom.sig available from the update service.
 
The simplest fix is to copy the pronom.sig file that is bundled with the source (at this path: https://github.com/richardlehane/siegfried/tree/master/cmd/roy/data) to your $HOME/siegfried directory. 

Your other option is to build the signature creation utility, roy, (go get github.com/richardlehane/siegfried/cmd/roy) and make your own signature files (https://github.com/richardlehane/siegfried/wiki/Building-a-signature-file-with-ROY).

**Comment by seamang** [comment]
Used the bundled file, works perfectly. Thanks for the instant response.

**Comment by richardlehane** [comment]
no worries, thanks for trying sf
