### ISSUE TITLE
Consider logging Errors by default to stderr

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#60]
Access issues have been dissipating silently in my SF output recently resulting in an incomplete analysis. 

Without SF failing completely on a folder scan or outputting any clues of a warning it's difficult to chase down depending on when one looks at the results. 

Can it be considered for errors to be sent to stderr by default, with it being quite easy to pipe either stdout or stderr on the command line rather than -log option. 

Or maybe an option to choose to quieten over an option to choose to log.

**Comment by richardlehane** [comment]
thx Ross I'll have a look at making error the default value of the -log flag, which will have the effect you are looking for (but will also allow users to quieten by going -log "")

Side note: do you consider zero-sized files an error - or should this just go under the warning field in the identification block?

**Comment by ross-spencer** [comment]
Good question, I've been looking at what is coming out on the log this afternoon. Zero files are what they are. We treat them as just another file we need to analyse, report on, and remove through disposal authority. So not an error. Though they are something users might want to treat seriously and answer about how they came to exist in their folders, e.g. if they turn up following a media extract.

**Comment by ross-spencer** [comment]
Are you using Go's log module throughout the code? - That is; I see output like this:

[FILE] e:\dir1\dir2\dir2\filename.pps
[ERROR] mscfb: error reading compound file

Doesn't log output datetime as well?

**Comment by richardlehane** [comment]
OK so -log error is now default: https://github.com/richardlehane/siegfried/commit/cef4f7f092af8d5e36f9414f6f4af2e104287be4

The log package is used a little but only for fatal errors where sf itself breaks. 

Could look at migrating to it for all logging (warnings, debug) but not sure if worth it (i.e. might be overkill since don't need to report on go src line numbers etc. because the errors aren't strictly sf errors, they are errors with the files themselves e.g. permissions, bad OLE, zero-sized etc.). Also some of the logging (slow, known, unknown) doesn't really fit in the log package's mould

Do you need datetime??? 

Would you like datetime?

**Comment by richardlehane** [comment]
p.s. a good blog post on log package: http://dave.cheney.net/2015/11/05/lets-talk-about-logging

**Comment by ross-spencer** [comment]
Thanks Richard. Will have a read. No don't need datetime :) Thank you though. I'm just being overly curious! ^_^;

**Comment by richardlehane** [comment]
cool, closing for now!
