### ISSUE TITLE
Use of 'version' in tika and freedesktop identification?

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#77]
Hi Richard,

Will version ever be used as a field for tika and freedesktop ID or are the following fields the only ones used?

    ns      : 
    id      : 
    format  : 
    mime    : 
    basis   : 
    warning : 

Thanks,

Ross

**Comment by richardlehane** [comment]
Hi Ross
no - the MIMEInfo spec doesn't have version, so that field isn't used for tika and freedesktop. The six fields you see above are the only ones that will be populated by those identifiers (and their CSV output will only be six columns, not seven like PRONOM).

The way the Identifier interface works, you don't have to return particular fields with results at all: they can return whatever JSON/YAML/CSV they like. Identifier's do have to implement a Fields() interface where they declare what fields they'll be returning so that clients can know ahead of time what they'll be getting. The benefit here is that future Identifiers could have additional fields if necessary (e.g. a Library of Congress FDD identifier might want to return additional info from that registry).

**Comment by ross-spencer** [comment]
Thanks Richard.
