### ISSUE TITLE
Siegfried crashes on OS X

### ISSUE THREAD

**Issue by workflowsguy** [richardlehane/siegfried#79]
Since today,
I experience various crashes when running Siegfried. E.g.

> sf -update 

gives

> panic: runtime error: makeslice: len out of range
> 
> goroutine 1 [running]:
> github.com/richardlehane/siegfried/pkg/core/stringmatcher.Load(0xc8200111a0, 0xece745e1a)
> 	/private/tmp/siegfried20160206-18769-14i816a/siegfried-1.4.5/src/github.com/richardlehane/siegfried/pkg/core/stringmatcher/stringmatcher.go:39 +0xf3
> github.com/richardlehane/siegfried.Load(0xc82000ec40, 0x3c, 0x0, 0x0, 0x0)
> 	/private/tmp/siegfried20160206-18769-14i816a/siegfried-1.4.5/src/github.com/richardlehane/siegfried/siegfried.go:187 +0xcc4
> main.updateSigs(0x0, 0x0, 0x0, 0x0)
> 	/private/tmp/siegfried20160206-18769-14i816a/siegfried-1.4.5/src/github.com/richardlehane/siegfried/cmd/sf/update.go:53 +0x2b2
> main.main()
> 	/private/tmp/siegfried20160206-18769-14i816a/siegfried-1.4.5/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:239 +0x5e0
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1
> 
> goroutine 18 [IO wait]:
> net.runtime_pollWait(0xe01000, 0x72, 0xc82000c140)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
> net.(*pollDesc).Wait(0xc8200f0060, 0x72, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
> net.(*pollDesc).WaitRead(0xc8200f0060, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
> net.(*netFD).Read(0xc8200f0000, 0xc8200f2000, 0x1000, 0x1000, 0x0, 0xaa0050, 0xc82000c140)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:232 +0x23a
> net.(*conn).Read(0xc8200ec008, 0xc8200f2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/net.go:172 +0xe4
> net/http.noteEOFReader.Read(0xe010c0, 0xc8200ec008, 0xc8200e4058, 0xc8200f2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1370 +0x67
> net/http.(*noteEOFReader).Read(0xc8200e0100, 0xc8200f2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
> 	<autogenerated>:126 +0xd0
> bufio.(*Reader).fill(0xc8200de180)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:97 +0x1e9
> bufio.(*Reader).Peek(0xc8200de180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:132 +0xcc
> net/http.(*persistConn).readLoop(0xc8200e4000)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:876 +0xf7
> created by net/http.(*Transport).dialConn
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:685 +0xc78
> 
> goroutine 19 [select]:
> net/http.(*persistConn).writeLoop(0xc8200e4000)
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1009 +0x40c
> created by net/http.(*Transport).dialConn
> 	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:686 +0xc9d

Similar with

> sf -version

which results in

> siegfried 1.4.5
> panic: runtime error: makeslice: len out of range
> 
> goroutine 1 [running]:
> github.com/richardlehane/siegfried/pkg/core/stringmatcher.Load(0xc820010f30, 0xece745e1a)
> 	/private/tmp/siegfried20160206-18769-14i816a/siegfried-1.4.5/src/github.com/richardlehane/siegfried/pkg/core/stringmatcher/stringmatcher.go:39 +0xf3
> github.com/richardlehane/siegfried.Load(0xc82000e940, 0x3c, 0x0, 0x0, 0x0)
> 	/private/tmp/siegfried20160206-18769-14i816a/siegfried-1.4.5/src/github.com/richardlehane/siegfried/siegfried.go:187 +0xcc4
> main.main()
> 	/private/tmp/siegfried20160206-18769-14i816a/siegfried-1.4.5/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:221 +0x2ae
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

I am using version 1.4.5 (this is the latest version available from there) installed via

> brew install mistydemeo/digipres/siegfried

Thanks!

**Comment by richardlehane** [comment]
Hi again Stefan,
I'm sorry for this... I thought I had fixed this issue, but evidently not.

The underlying problem is that because there is a new sf 1.5.x series, the update service no longer works for older versions of sf (1.4.5 and <). This is how it should be, however, those older versions *should* prevent the update and fail gracefully by returning a warning & not blowing up like that!

I'll look into this bug to try to make sure that the process for updates is smoother in future.

In the meantime, the fixes for you are:

1. repair your sf 1.4.5 signatures

or 

2. update to sf 1.5.0.

Re. 1:

  - you can repair your sf 1.4.5 signatures by entering the command `roy build`
  - this may mean you are running an older version of PRONOM (check with `sf -version`, it should be v84). You can update to latest pronom by grabbing the data_1-5-0.zip file from https://github.com/richardlehane/siegfried/releases, unpacking to your sf home directory (probably /usr/local/Cellar/siegfried/1.4.5), and then running `roy build`.

Re. 2:

  - I have submitted a pull request for an update to sf 1.5.0. If you're willing to diverge from Misty's digipres tap (and I wouldn't necessarily advise that!), you *could* install my pull request by installing from my fork on github. To do this, first uninstall (`brew uninstall siegfried`) and then re-install from my tap: (`brew install richardlehane/digipres/siegfried`). My tap is often a release or two ahead of Misty's for siegfried, but installing from it has the disadvantage that I only keep track of siegfried so might well fall behind on the other packages in digipres tap... and also my fork hasn't had benefit of QA by Misty who is a brew expert.

**Comment by workflowsguy** [comment]
Thank you Richard,

I have rebuilt the signature files with roy (had completely forgotten about this possiblity) and will wait till version 1.5 becomes available through Misty's tap.

Cheers!
